// Generated by Opus 4.8
#ifndef CHACHA20_H
#define CHACHA20_H

#include <stdint.h>

#define CHACHA20_KEY_SIZE   32
#define CHACHA20_NONCE_SIZE 12
#define CHACHA20_TAG_SIZE   16

/* ChaCha20-Poly1305 AEAD (RFC 8439).
 * Returns 0 on success, -1 if tag verification fails (decrypt only). */

int chacha20poly1305_encrypt(
    const uint8_t key[CHACHA20_KEY_SIZE],
    const uint8_t nonce[CHACHA20_NONCE_SIZE],
    const uint8_t *plain, int plain_len,
    uint8_t *cipher_out,
    uint8_t tag_out[CHACHA20_TAG_SIZE]);

int chacha20poly1305_decrypt(
    const uint8_t key[CHACHA20_KEY_SIZE],
    const uint8_t nonce[CHACHA20_NONCE_SIZE],
    const uint8_t *cipher, int cipher_len,
    const uint8_t tag[CHACHA20_TAG_SIZE],
    uint8_t *plain_out);

#endif
