// Generated by Opus 4.8
#include "chacha20.h"
#include <string.h>

/* ---- ChaCha20 (RFC 8439 section 2.1) ------------------------------------ */

#define ROTL32(v, n) (((v) << (n)) | ((v) >> (32 - (n))))

#define QR(a, b, c, d) \
    a += b; d ^= a; d = ROTL32(d, 16); \
    c += d; b ^= c; b = ROTL32(b, 12); \
    a += b; d ^= a; d = ROTL32(d,  8); \
    c += d; b ^= c; b = ROTL32(b,  7)

static uint32_t load32_le(const uint8_t *p)
{
    return (uint32_t)p[0]
         | ((uint32_t)p[1] <<  8)
         | ((uint32_t)p[2] << 16)
         | ((uint32_t)p[3] << 24);
}

static void store32_le(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)(v      );
    p[1] = (uint8_t)(v >>  8);
    p[2] = (uint8_t)(v >> 16);
    p[3] = (uint8_t)(v >> 24);
}

/* "expand 32-byte k" as four little-endian uint32 constants */
static const uint32_t SIGMA[4] = {
    0x61707865, 0x3320646e, 0x79622d32, 0x6b206574
};

static void chacha20_block(uint32_t out[16], const uint32_t in[16])
{
    uint32_t x[16];
    int i;
    for (i = 0; i < 16; i++) x[i] = in[i];

    for (i = 0; i < 10; i++) {
        QR(x[0], x[4], x[ 8], x[12]);
        QR(x[1], x[5], x[ 9], x[13]);
        QR(x[2], x[6], x[10], x[14]);
        QR(x[3], x[7], x[11], x[15]);
        QR(x[0], x[5], x[10], x[15]);
        QR(x[1], x[6], x[11], x[12]);
        QR(x[2], x[7], x[ 8], x[13]);
        QR(x[3], x[4], x[ 9], x[14]);
    }

    for (i = 0; i < 16; i++) out[i] = x[i] + in[i];
}

static void chacha20_init(uint32_t state[16],
                          const uint8_t key[32],
                          uint32_t counter,
                          const uint8_t nonce[12])
{
    state[ 0] = SIGMA[0];
    state[ 1] = SIGMA[1];
    state[ 2] = SIGMA[2];
    state[ 3] = SIGMA[3];
    state[ 4] = load32_le(key +  0);
    state[ 5] = load32_le(key +  4);
    state[ 6] = load32_le(key +  8);
    state[ 7] = load32_le(key + 12);
    state[ 8] = load32_le(key + 16);
    state[ 9] = load32_le(key + 20);
    state[10] = load32_le(key + 24);
    state[11] = load32_le(key + 28);
    state[12] = counter;
    state[13] = load32_le(nonce + 0);
    state[14] = load32_le(nonce + 4);
    state[15] = load32_le(nonce + 8);
}

static void chacha20_xor(const uint8_t key[32],
                         uint32_t counter,
                         const uint8_t nonce[12],
                         uint8_t *data, int len)
{
    uint32_t state[16], block[16];
    uint8_t  keystream[64];
    int i, j;

    chacha20_init(state, key, counter, nonce);

    i = 0;
    while (i < len) {
        chacha20_block(block, state);
        state[12]++;

        for (j = 0; j < 16; j++) store32_le(keystream + j * 4, block[j]);

        for (j = 0; j < 64 && i < len; j++, i++)
            data[i] ^= keystream[j];
    }
}

/* ---- Poly1305 (RFC 8439 section 2.5) ------------------------------------ */
/* 26-bit limb representation so multiplications fit in uint64_t on 32-bit CPUs */

typedef struct {
    uint32_t r[5];       /* clamped key r, 26-bit limbs */
    uint32_t h[5];       /* accumulator, 26-bit limbs   */
    uint32_t pad[4];     /* key s (add-at-end)           */
    uint8_t  buf[16];    /* partial block buffer         */
    int      buf_len;
} poly1305_ctx;

static void poly1305_init(poly1305_ctx *ctx, const uint8_t key[32])
{
    uint32_t t0 = load32_le(key +  0);
    uint32_t t1 = load32_le(key +  4);
    uint32_t t2 = load32_le(key +  8);
    uint32_t t3 = load32_le(key + 12);

    /* clamp r (RFC 8439 section 2.5.1) */
    ctx->r[0] =   t0                       & 0x3ffffff;
    ctx->r[1] = ((t0 >> 26) | (t1 <<  6)) & 0x3ffff03;
    ctx->r[2] = ((t1 >> 20) | (t2 << 12)) & 0x3ffc0ff;
    ctx->r[3] = ((t2 >> 14) | (t3 << 18)) & 0x3f03fff;
    ctx->r[4] =  (t3 >>  8)               & 0x00fffff;

    ctx->pad[0] = load32_le(key + 16);
    ctx->pad[1] = load32_le(key + 20);
    ctx->pad[2] = load32_le(key + 24);
    ctx->pad[3] = load32_le(key + 28);

    ctx->h[0] = ctx->h[1] = ctx->h[2] = ctx->h[3] = ctx->h[4] = 0;
    ctx->buf_len = 0;
}

/* Process one 16-byte block. final=1 means partial block already padded
 * with 0x01 — skip the separate 2^128 term. */
static void poly1305_block(poly1305_ctx *ctx, const uint8_t *m, int final)
{
    uint32_t r0 = ctx->r[0], r1 = ctx->r[1], r2 = ctx->r[2],
             r3 = ctx->r[3], r4 = ctx->r[4];
    uint32_t s1 = r1 * 5,   s2 = r2 * 5, s3 = r3 * 5, s4 = r4 * 5;
    uint32_t h0 = ctx->h[0], h1 = ctx->h[1], h2 = ctx->h[2],
             h3 = ctx->h[3], h4 = ctx->h[4];
    uint32_t c;
    uint64_t d0, d1, d2, d3, d4;

    uint32_t t0 = load32_le(m +  0);
    uint32_t t1 = load32_le(m +  4);
    uint32_t t2 = load32_le(m +  8);
    uint32_t t3 = load32_le(m + 12);

    h0 +=   t0                       & 0x3ffffff;
    h1 += ((t0 >> 26) | (t1 <<  6)) & 0x3ffffff;
    h2 += ((t1 >> 20) | (t2 << 12)) & 0x3ffffff;
    h3 += ((t2 >> 14) | (t3 << 18)) & 0x3ffffff;
    h4 +=  (t3 >>  8) | (final ? 0u : (1u << 24));

    d0 = (uint64_t)h0*r0 + (uint64_t)h1*s4 + (uint64_t)h2*s3
       + (uint64_t)h3*s2 + (uint64_t)h4*s1;
    d1 = (uint64_t)h0*r1 + (uint64_t)h1*r0 + (uint64_t)h2*s4
       + (uint64_t)h3*s3 + (uint64_t)h4*s2;
    d2 = (uint64_t)h0*r2 + (uint64_t)h1*r1 + (uint64_t)h2*r0
       + (uint64_t)h3*s4 + (uint64_t)h4*s3;
    d3 = (uint64_t)h0*r3 + (uint64_t)h1*r2 + (uint64_t)h2*r1
       + (uint64_t)h3*r0 + (uint64_t)h4*s4;
    d4 = (uint64_t)h0*r4 + (uint64_t)h1*r3 + (uint64_t)h2*r2
       + (uint64_t)h3*r1 + (uint64_t)h4*r0;

    c = (uint32_t)(d0 >> 26); h0 = (uint32_t)d0 & 0x3ffffff; d1 += c;
    c = (uint32_t)(d1 >> 26); h1 = (uint32_t)d1 & 0x3ffffff; d2 += c;
    c = (uint32_t)(d2 >> 26); h2 = (uint32_t)d2 & 0x3ffffff; d3 += c;
    c = (uint32_t)(d3 >> 26); h3 = (uint32_t)d3 & 0x3ffffff; d4 += c;
    c = (uint32_t)(d4 >> 26); h4 = (uint32_t)d4 & 0x3ffffff;
    h0 += c * 5;
    c = h0 >> 26; h0 &= 0x3ffffff; h1 += c;

    ctx->h[0] = h0; ctx->h[1] = h1; ctx->h[2] = h2;
    ctx->h[3] = h3; ctx->h[4] = h4;
}

static void poly1305_update(poly1305_ctx *ctx, const uint8_t *m, int len)
{
    int i, want;

    if (ctx->buf_len > 0) {
        want = 16 - ctx->buf_len;
        if (want > len) want = len;
        for (i = 0; i < want; i++)
            ctx->buf[ctx->buf_len + i] = m[i];
        ctx->buf_len += want;
        m   += want;
        len -= want;
        if (ctx->buf_len == 16) {
            poly1305_block(ctx, ctx->buf, 0);
            ctx->buf_len = 0;
        }
    }

    while (len >= 16) {
        poly1305_block(ctx, m, 0);
        m   += 16;
        len -= 16;
    }

    for (i = 0; i < len; i++)
        ctx->buf[i] = m[i];
    ctx->buf_len = len;
}

static void poly1305_finish(poly1305_ctx *ctx, uint8_t tag[16])
{
    uint32_t h0, h1, h2, h3, h4, c;
    uint32_t g0, g1, g2, g3, g4;
    uint32_t mask;
    uint64_t f;

    if (ctx->buf_len > 0) {
        ctx->buf[ctx->buf_len++] = 0x01;
        while (ctx->buf_len < 16)
            ctx->buf[ctx->buf_len++] = 0x00;
        poly1305_block(ctx, ctx->buf, 1);
    }

    h0 = ctx->h[0]; h1 = ctx->h[1]; h2 = ctx->h[2];
    h3 = ctx->h[3]; h4 = ctx->h[4];

    /* fully carry */
    c = h1 >> 26; h1 &= 0x3ffffff; h2 += c;
    c = h2 >> 26; h2 &= 0x3ffffff; h3 += c;
    c = h3 >> 26; h3 &= 0x3ffffff; h4 += c;
    c = h4 >> 26; h4 &= 0x3ffffff; h0 += c * 5;
    c = h0 >> 26; h0 &= 0x3ffffff; h1 += c;

    /* compute h - p = h + 5, propagate */
    g0 = h0 + 5; c = g0 >> 26; g0 &= 0x3ffffff;
    g1 = h1 + c; c = g1 >> 26; g1 &= 0x3ffffff;
    g2 = h2 + c; c = g2 >> 26; g2 &= 0x3ffffff;
    g3 = h3 + c; c = g3 >> 26; g3 &= 0x3ffffff;
    g4 = h4 + c - (1u << 26);

    /* select h if h < p, else h - p */
    mask = (g4 >> 31) - 1;
    g0 &= mask; g1 &= mask; g2 &= mask; g3 &= mask; g4 &= mask;
    mask = ~mask;
    h0 = (h0 & mask) | g0; h1 = (h1 & mask) | g1;
    h2 = (h2 & mask) | g2; h3 = (h3 & mask) | g3;
    h4 = (h4 & mask) | g4;

    /* convert limbs to four 32-bit words */
    h0 = ((h0      ) | (h1 << 26)) & 0xffffffffu;
    h1 = ((h1 >>  6) | (h2 << 20)) & 0xffffffffu;
    h2 = ((h2 >> 12) | (h3 << 14)) & 0xffffffffu;
    h3 = ((h3 >> 18) | (h4 <<  8)) & 0xffffffffu;

    /* add s */
    f = (uint64_t)h0 + ctx->pad[0];              h0 = (uint32_t)f;
    f = (uint64_t)h1 + ctx->pad[1] + (f >> 32);  h1 = (uint32_t)f;
    f = (uint64_t)h2 + ctx->pad[2] + (f >> 32);  h2 = (uint32_t)f;
    f = (uint64_t)h3 + ctx->pad[3] + (f >> 32);  h3 = (uint32_t)f;

    store32_le(tag +  0, h0);
    store32_le(tag +  4, h1);
    store32_le(tag +  8, h2);
    store32_le(tag + 12, h3);
}

/* Feed padding zeros to align to 16-byte boundary */
static void poly1305_pad16(poly1305_ctx *ctx, int data_len)
{
    static const uint8_t zeros[16] = {0};
    int pad = (16 - (data_len & 15)) & 15;
    if (pad > 0) poly1305_update(ctx, zeros, pad);
}

/* Feed a 64-bit length as 8 little-endian bytes */
static void poly1305_encode_len(poly1305_ctx *ctx, uint64_t len)
{
    uint8_t buf[8];
    buf[0] = (uint8_t)(len      ); buf[1] = (uint8_t)(len >>  8);
    buf[2] = (uint8_t)(len >> 16); buf[3] = (uint8_t)(len >> 24);
    buf[4] = (uint8_t)(len >> 32); buf[5] = (uint8_t)(len >> 40);
    buf[6] = (uint8_t)(len >> 48); buf[7] = (uint8_t)(len >> 56);
    poly1305_update(ctx, buf, 8);
}

/* ---- ChaCha20-Poly1305 AEAD (RFC 8439 section 2.8) ---------------------- */

static void make_poly1305_key(const uint8_t key[32],
                               const uint8_t nonce[12],
                               uint8_t otk[32])
{
    uint32_t state[16], block[16];
    int i;
    chacha20_init(state, key, 0, nonce);
    chacha20_block(block, state);
    for (i = 0; i < 8; i++) store32_le(otk + i * 4, block[i]);
}

static void compute_tag(const uint8_t otk[32],
                         const uint8_t *cipher, int cipher_len,
                         uint8_t tag[CHACHA20_TAG_SIZE])
{
    poly1305_ctx mac;
    poly1305_init(&mac, otk);
    /* No AAD in our scheme — per RFC 8439: pad16(aad) || pad16(ct) || len_aad || len_ct */
    poly1305_pad16(&mac, 0);                        /* pad16(empty aad) = nothing */
    poly1305_update(&mac, cipher, cipher_len);
    poly1305_pad16(&mac, cipher_len);
    poly1305_encode_len(&mac, 0);                   /* aad length = 0 */
    poly1305_encode_len(&mac, (uint64_t)cipher_len);
    poly1305_finish(&mac, tag);
}

int chacha20poly1305_encrypt(
    const uint8_t key[CHACHA20_KEY_SIZE],
    const uint8_t nonce[CHACHA20_NONCE_SIZE],
    const uint8_t *plain, int plain_len,
    uint8_t *cipher_out,
    uint8_t tag_out[CHACHA20_TAG_SIZE])
{
    uint8_t otk[32];

    make_poly1305_key(key, nonce, otk);

    memcpy(cipher_out, plain, plain_len);
    chacha20_xor(key, 1, nonce, cipher_out, plain_len); /* counter starts at 1 */

    compute_tag(otk, cipher_out, plain_len, tag_out);
    return 0;
}

int chacha20poly1305_decrypt(
    const uint8_t key[CHACHA20_KEY_SIZE],
    const uint8_t nonce[CHACHA20_NONCE_SIZE],
    const uint8_t *cipher, int cipher_len,
    const uint8_t tag[CHACHA20_TAG_SIZE],
    uint8_t *plain_out)
{
    uint8_t otk[32], computed_tag[CHACHA20_TAG_SIZE];
    uint8_t diff;
    int i;

    make_poly1305_key(key, nonce, otk);
    compute_tag(otk, cipher, cipher_len, computed_tag);

    /* constant-time comparison — avoids timing oracle on the tag */
    diff = 0;
    for (i = 0; i < CHACHA20_TAG_SIZE; i++)
        diff |= computed_tag[i] ^ tag[i];
    if (diff != 0) return -1;

    memcpy(plain_out, cipher, cipher_len);
    chacha20_xor(key, 1, nonce, plain_out, cipher_len);
    return 0;
}
