// Generated by Opus 4.8
#include "crypt_chacha.h"
#include "chacha20.h"
#include "../sha1.h"
#include <string.h>

#define SALT_LEN  16
#define NONCE_LEN 12
#define TAG_LEN   16

/* Derive a 32-byte ChaCha20 key from passphrase + salt using two SHA-1 rounds.
 * SHA-1 gives 20 bytes; we need 32, so we hash twice with a 1-byte separator. */
static void derive_key(const char *passphrase, const uint8_t *salt,
                       uint8_t key[CHACHA20_KEY_SIZE])
{
    struct sha1 ctx;
    uint8_t h1[SHA1HashSize], h2[SHA1HashSize];
    const uint8_t sep0 = 0x00, sep1 = 0x01;
    int pass_len = 0;
    const char *p = passphrase;
    while (*p++) pass_len++;

    sha1_reset(&ctx);
    sha1_input(&ctx, (uint8_t *)passphrase, pass_len);
    sha1_input(&ctx, salt, SALT_LEN);
    sha1_input(&ctx, &sep0, 1);
    sha1_result(&ctx, h1);

    sha1_reset(&ctx);
    sha1_input(&ctx, (uint8_t *)passphrase, pass_len);
    sha1_input(&ctx, salt, SALT_LEN);
    sha1_input(&ctx, &sep1, 1);
    sha1_result(&ctx, h2);

    memcpy(key,      h1, SHA1HashSize);                        /* 20 bytes */
    memcpy(key + 20, h2, CHACHA20_KEY_SIZE - SHA1HashSize);    /* 12 bytes */
}

int crypt_encrypt(const char *passphrase,
                  const uint8_t *plain, int plain_len,
                  uint8_t *out,
                  uint8_t (*rand_byte)(void))
{
    uint8_t salt[SALT_LEN], nonce[NONCE_LEN], key[CHACHA20_KEY_SIZE];
    uint8_t *cipher, *tag;
    int i;

    for (i = 0; i < SALT_LEN;  i++) salt[i]  = rand_byte();
    for (i = 0; i < NONCE_LEN; i++) nonce[i] = rand_byte();

    derive_key(passphrase, salt, key);

    memcpy(out,             salt,  SALT_LEN);
    memcpy(out + SALT_LEN,  nonce, NONCE_LEN);

    cipher = out + SALT_LEN + NONCE_LEN;
    tag    = cipher + plain_len;

    chacha20poly1305_encrypt(key, nonce, plain, plain_len, cipher, tag);

    return plain_len + CRYPT_OVERHEAD;
}

int crypt_decrypt(const char *passphrase,
                  const uint8_t *cipher, int cipher_len,
                  uint8_t *out)
{
    uint8_t key[CHACHA20_KEY_SIZE];
    const uint8_t *salt, *nonce, *ct, *tag;
    int ct_len;

    if (cipher_len < CRYPT_OVERHEAD) return -1;

    salt  = cipher;
    nonce = cipher + SALT_LEN;
    ct    = cipher + SALT_LEN + NONCE_LEN;
    ct_len = cipher_len - CRYPT_OVERHEAD;
    tag   = ct + ct_len;

    derive_key(passphrase, salt, key);

    if (chacha20poly1305_decrypt(key, nonce, ct, ct_len, tag, out) != 0)
        return -1;

    return ct_len;
}
