// Generated by Opus 4.8
#ifndef CRYPT_CHACHA_H
#define CRYPT_CHACHA_H

#include <stdint.h>

/* Bytes added to plaintext length by crypt_encrypt: 16 salt + 12 nonce + 16 tag */
#define CRYPT_OVERHEAD  44

/*
 * File format produced by crypt_encrypt:
 *   [ salt 16 bytes ][ nonce 12 bytes ][ ciphertext N bytes ][ tag 16 bytes ]
 *
 * out must be at least plain_len + CRYPT_OVERHEAD bytes.
 * rand_byte() is called to fill salt and nonce — pass a wrapper around your
 * platform's random source (rand() on Mac, rb->rand() on Rockbox).
 * Returns total bytes written (plain_len + CRYPT_OVERHEAD).
 */
int crypt_encrypt(const char *passphrase,
                  const uint8_t *plain, int plain_len,
                  uint8_t *out,
                  uint8_t (*rand_byte)(void));

/*
 * Returns decrypted length on success, -1 if passphrase is wrong or
 * ciphertext was tampered with.
 * out must be at least cipher_len - CRYPT_OVERHEAD bytes.
 */
int crypt_decrypt(const char *passphrase,
                  const uint8_t *cipher, int cipher_len,
                  uint8_t *out);

#endif
